USE mysql_project_db;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL
);

CREATE TABLE movies (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(200) NOT NULL,
  year INT NOT NULL,
  rated VARCHAR(10) NOT NULL,
  runtime VARCHAR(100) NOT NULL,
  director VARCHAR(200) NOT NULL,
  plot VARCHAR(2000) NOT NULL,
  on_list BOOLEAN DEFAULT false,
  is_watched BOOLEAN DEFAULT false,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);
